# Site settings
name: Less Or More
email: haeyong.hwang27@gmail.com
author: Haeyong Hwang
url: http://haeyong27.github.io/
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/haeyong27/
baseurl: ""
description: Actually, less is more!
meta_description: meta description
motto: It's our wits that make us men.
banner: banner

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: haeyong27

# Build settings
markdown: kramdown